### ISSUE TITLE
Garbage collecting old Docker images

### ISSUE THREAD

**Issue by quinnypig** [jobinbasani/aws-lambda-website-to-pdf#2]
Every `cdk deploy` that changes the code of the function itself results in a fresh (large) Docker image hanging around. Is there something I'm missing as far as how to responsibly build layers / garbage collect the old versions so it doesn't eat my disk alive?

**Comment by jobinbasani** [comment]
That's true, not sure if CDK can take care of the older images.
You can [prune the system](https://docs.docker.com/engine/reference/commandline/system_prune/) as an alternative.

**Comment by quinnypig** [comment]
Thanks for the response! I tried that, for some reason it seems to think that I'm still using a pile of the older images:

https://shitposting.pictures/5OGWnURRobmG

**Comment by jobinbasani** [comment]
That's strange. I tried `docker system prune -a` and it cleaned up pretty much everything for me.

**Comment by quinnypig** [comment]
Well, the `-a` flag certainly worked, and is new to me; thanks!

**Comment by jobinbasani** [comment]
Closing this issue since older images can be handled by Docker itself, and not by CDK.
